- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/dupes
      - homebrew/science
      - caskroom/cask
      - homebrew/binary

    homebrew_packages:
      - { name: ansible }
      - { name: autoconf }
      - { name: automake }
      - { name: autotools }
      - { name: curl }
      - { name: gcc }
      - { name: gdb }
      - { name: git }
      - { name: imagemagick }
      - { name: libjpeg }
      - { name: libpng }
      - { name: libtiff }
      - { name: libtool }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: peco }
      - { name: pkg-config }
      - { name: mosh }
      - { name: nmap }
      - { name: node }
      - { name: python }
      - { name: readline }
      - { name: ruby }
      - { name: thefuck }
      - { name: tig }
      - { name: tmux }
      - { name: tree }
      - { name: vim, install_options: with-lua }
      - { name: wget }
      - { name: xz }
      - { name: zsh, install_options: disable-etcdir }
      - { name: zsh-autosuggestions }
      - { name: zsh-completions }
      - { name: zsh-syntax-highlighting }

    homebrew_cask_packages:
      - { name: alfred }
      - { name: bartender }
      - { name: caffeine }
      - { name: docker }
      - { name: dropbox }
      - { name: firefox }
      - { name: google-chrome }
      - { name: google-japanese-ime }
      - { name: iterm2 }
      - { name: karabiner-elements }
      - { name: keybase }
      - { name: slack }
      - { name: the-unarchiver }
      - { name: virtualbox-extension-pack }
      - { name: vagrant }
      - { name: virtualbox }
      - { name: webstorm }
      - { name: wireshark }

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'
